VehicleInsurance/Controllers/KhachHangController.cs
using Microsoft.AspNetCore.Mvc;
using VehicleInsurance.Data;
using VehicleInsurance.Models;

namespace VehicleInsurance.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly VehicleInsuranceContext db;

        public KhachHangController(VehicleInsuranceContext context)
        {
            db=context;
        }
        [HttpGet]
        public IActionResult DangKy()
        {
            return View();
        }
        
    }
}

VehicleInsurance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleInsurance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="apple-touch-icon" sizes="180x180" href="assets/img/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/img/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicons/favicon.ico">
    <link rel="manifest" href="assets/img/favicons/manifest.json">
    <meta name="msapplication-TileImage" content="assets/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700;800&amp;display=swap" rel="stylesheet">
    <link href="vendors/prism/prism.css" rel="stylesheet">
    <link href="assets/css/theme.css" rel="stylesheet" />
    <link href="assets/css/user.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand" href="index.html"><span class="text-primary fs-3 ms-2 fw-bolder">en</span><span class="fw-thin text-300 fs-3">surance</span></a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse pt-4 pt-lg-0" id="navbarSupportedContent">
                    <p class="mb-0 ms-auto text-light fs-0 fw-normal"><i class="fas fa-phone-alt me-2"></i>Call Us Now <a class="text-light" href="tel:+604-680-9785">+215(362)4579</a></p>
                    <ul class="navbar-nav ms-auto border-bottom border-lg-bottom-0 pt-2 pt-lg-0">
                        <li class="nav-item px-2"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item px-2"><a asp-action="TinhToan" class="nav-link">Products</a></li>
                        <li class="nav-item px-2"><a class="nav-link" href="#news">Contact us</a></li>
                        <li class="nav-item px-2"><a asp-controller="KhachHang" asp-action="DangKy" class="nav-link" >Dang Ky</a></li>
                        <li class="nav-item px-2"><a asp-controller="KhachHang" asp-action="DangKy" class="nav-link" >Dang Nhap</a></li>
                    </ul>
                    <partial name="_LoginPartial"/>
                    <div class="d-flex mt-2 align-items-center mt-lg-0">
                        <div class="dropdown">
                            <button class="btn btn-sm d-flex mx-2" id="dropdownMenuButton1" type="submit" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-search text-primary"></i></button>
                            <div class="dropdown-menu dropdown-menu-lg-end p-0 rounded" aria-labelledby="dropdownMenuButton1" style="top:55px">
                                <form>
                                    <input class="form-control form-search-control border-100" type="search" placeholder="Search" aria-label="Search" />
                                </form>
                            </div>
                        </div><a href="#!"> <i class="fas fa-user text-primary"> </i></a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - VehicleInsurance - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="vendors/popper/popper.min.js"></script>
    <script src="vendors/bootstrap/bootstrap.min.js"></script>
    <script src="vendors/anchorjs/anchor.min.js"></script>
    <script src="vendors/is/is.min.js"></script>
    <script src="vendors/fontawesome/all.min.js"></script>
    <script src="vendors/lodash/lodash.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="vendors/prism/prism.js"></script>
    <script src="assets/js/theme.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>